---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: [ 'tinc' ]
    attributes:
      tinc:
        network_name: "test"
        private_ip: "10.0.0.1"
        netmask: "255.255.0.0"
