---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: [ 'tinc' ]
    attributes:
      tinc:
        networks:
          - network_name: "test"
            private_ip: "10.0.0.1"
            netmask: "255.255.0.0"
            listen_port: 665
          - network_name: "test2"
            private_ip: "10.254.0.1"
            netmask: "255.255.0.0"
            listen_port: 666
